package dev.isnow.sixhundredelo.sdk.offset;

import lombok.experimental.UtilityClass;

@UtilityClass
public class Offsets
{
    public long m_pCameraServices = 0x0;
    public long m_iFOV = 0x0;
    public long m_bIsScoped = 0x0;
    public long m_iHealth = 0x0;
    public long m_entitySpottedState = 0x0;
    public long m_bSpotted = 0x0;
    public long m_iIDEntIndex = 0x0;
    public long m_pSceneNode = 0x0;
    public long dwViewMatrix = 0x0;
    public long m_vecViewOffset = 0x0;
    public long dwViewAngles = 0x0;
    public long m_lifeState = 0x0;
    public long m_vOldOrigin = 0x0;
    public long m_iTeamNum = 0x0;
    public long m_hPlayerPawn = 0x0;
    public long dwLocalPlayerPawn = 0x0;
    public long dwEntityList = 0x0;
    public long m_flFlashBangTime = 0x0;
    public long m_modelState = 0x0;
    public long m_pGameSceneNode = 0x0;
    public long dwCSGOInput = 0x0;
    public long m_flC4Blow = 0x0;
    public long current_time = 0x0;
    public long dwGlobalVars = 0x0;
    public long dwPlantedC4 = 0x0;
    public long m_bBombPlanted = 0x0;
    public long dwGameRules = 0x0;
    public long dwSensitivity_sensitivity = 0x0;
    public long dwSensitivity = 0x0;
    public long m_iszPlayerName = 0x0;
    public long m_pClippingWeapon = 0x0;
    public long m_Item = 0x0;
    public long m_iItemDefinitionIndex = 0x0;
    public long m_AttributeManager = 0x0;
    public long attack = 0x0;
    public long jump = 0x0;
    public long m_bSpottedByMask = 0x0;
    public long m_pWeaponServices = 0x0;
    public long m_hActiveWeapon = 0x0;
    public long m_vecAbsVelocity = 0x0;
    public long m_fFlags = 0x0;
    public long m_hMyWeapons = 0x0;
    public long m_aimPunchAngle = 0x00;
    public long m_nCurrentTickThisFrame = 0x0;
    public long m_ArmorValue = 0x0;
    public long m_pInGameMoneyServices = 0x0;
    public long m_iAccount = 0x0;
    public long m_iTotalCashSpent = 0x0;
    public long m_iCashSpentThisRound = 0x0;
    public long m_aimPunchCache = 0x0;
    public long m_bIsBuyMenuOpen = 0x0;
    public long m_iAmmo = 0x0;
    public long m_angEyeAngles = 0x0;
    public long m_iShotsFired = 0x0;
    public long m_pActionTrackingServices = 0x0;
    public long m_iNumRoundKills = 0x0;
    public long m_iNumRoundKillsHeadshots = 0x0;
    public long m_flTotalRoundDamageDealt = 0x0;
    public long m_pBulletServices = 0x0;
    public long m_totalHitsOnServer = 0x0;
    public long m_iSpectatorSlotCount = 0x0;
    public long m_iPing = 0x0;
    public long m_bIsWalking = 0x0;
    public long dwLocalPlayerController = 0x0;
    public long m_bIsDefusing = 0x0;
    public long m_bInBombZone = 0x0;
    public long m_vecAbsOrigin = 0x0;
    public long m_GunGameImmunityColor = 0x0;
    public long m_flEmitSoundTime = 0x0;
    public long m_nFallbackPalongKit = 0x0;
    public long m_iItemIDHigh = 0x0;
    public long m_nFallbackSeed = 0x0;
    public long m_flFallbackWear = 0x0;
    public long m_weaponMode = 0x0;
}